spack/configs/summit/compilers.yaml
spack/configs/summit/packages.yaml

Spack does not clean the environment enough on Summit to use hard coded paths for the compilers and mpi when default modules are loaded in the shell (xl and spectrum-mpi built with xl).  An alternative is to ask users to purge their modules (or at least some of them) before using our spack packages.  To avoid this step, and possible problems/errors associated with it, I propose we use modules instead of paths on Summit for compilers and mpi.  For other libraries, I don't think using the system modules is critical as they are less likely to make significant changes to the environment.
With this PR, I am able to build xgc1 on summit using gcc/8.1.1 and Spectrum-MPI.  The gene install just ~~started~~ completed successfully.
For the record, my build process was:
```console
git clone …
```

Summit config: use modules for compilers and mpi

---

docs/index.rst
docs/machines/aimos.rst

Instructions for building GENE on the RPI AiMOS (mini summit) system with cmake are provided for developers of the coupler.

building gene on aimos w/cmake for coupler devs

---

spack/wdmapp/packages/gene/package.py
spack/wdmapp/packages/perfstubs/package.py
spack/wdmapp/packages/wdmapp/package.py
spack/wdmapp/packages/xgc1/package.py

* update XGC1 package with camtimers variant
* update GENE for `coupling` branch and corresponding variants
* add a `wdmapp` meta-package that pulls in XGC1 and GENE in the configs needed for coupling
It's highly likely that the variants will go through some consolidation/cleanup later, but for now this gets everything into place for coupling new GENE and old XGC1.

wdmapp spack package

---

spack/wdmapp/packages/coupler/package.py
spack/wdmapp/packages/kokkos/package.py
spack/wdmapp/packages/wdmapp/package.py

This PR adds a spack package for the xgc-gene coupler and lists it in wdmapp package.  I successfully installed all three via spack with `spack install wdmapp` on Summit using GCC 8.1 and Spectrum MPI as defined in [packages.yaml](https://github.com/wdmapp/wdmapp-config/blob/d64c9f004f515beaaf10c53c95f9c0e5bc714de9/summit/spack/packages.yaml) and [compilers.yaml](https://github.com/wdmapp/wdmapp-config/blob/d64c9f004f515beaaf10c53c95f9c0e5bc714de9/summit/spack/compilers.yaml).
Note, the coupler depends on [a spack fix for the kokkos package](https://github.com/spack/spack/pull/16237) that currently only exists in the spack `develop` branch.

Add spack package for coupler and list it in wdmapp package

---

docs/machines/aimos.rst

Manual cmake build instructions for https://github.com/wdmapp/XGC-Devel/tree/cfa6d816c1c012ca19eac88fe82fbe5999a80e17 on AiMOS.
Note, these instructions rely on a heavy dose of assumptions on which XGC compile flags should be enabled:
https://github.com/wdmapp/XGC-Devel/blob/cfa6d816c1c012ca19eac88fe82fbe5999a80e17/CMakeLists.txt#L31-L41

aimos: xgc-devel cmake instructions

---

spack/wdmapp/packages/kokkos/package.py
spack/wdmapp/packages/wdmapp/package.py
spack/wdmapp/packages/xgc-devel/package.py

This PR adds a package for the `rpi` branch of XGC-Devel.  
There are three commits:
- `xgc-devel` package: https://github.com/wdmapp/wdmapp-config/commit/28470f0fc9317c58491633b855a4b5bb41b8b7d9 
- `kokkos` package update to list latest tagged versions: https://github.com/wdmapp/wdmapp-config/commit/51d348fe76d4f6f537dca55aabd2418de83ced10 . Spack PR https://github.com/spack/spack/pull/16354 .
- `wdmapp` package installs `xgc-devel@rpi` . https://github.com/wdmapp/wdmapp-config/commit/9accc0294e21b4daff3ed9fb1600ef669686ed1b
The `rpi` branch has a few commits to support the install via CMake:
- build with CMake without using machine specific include files:
https://github.com/wdmapp/XGC-Devel/commit/6fa9de106484526258a87dcdf776d2ae425a3937 …

Add XGC-Devel

---

docs/machines/longhorn.rst
docs/machines/summit.rst
spack/wdmapp/packages/wdmapp/package.py

* make the "wdmapp" branch of XGC-Devel the branch to be used in the `wdmapp` bundle package
* use the "perfstubs" profiling option for GENE in the `wdmapp` bundle package
* also fix two links in the docs

Some "wdmapp" spack package updates

---

summit/spack/packages.yaml

By default, spack's libfabric won't include RDMA support, and after enabling
it, the spack-built rdma-core interferes with what spectrum-mpi uses, so this
makes it use the system rdma-core.
Thanks to @philip-davis and @gmerlo.

spack/summit: build RDMA-enabled libfabric / adios2

---

spack/wdmapp/packages/wdmapp/package.py

For adiabatic e- coupling, a non-cabana XGC-Devel is needed.

spack: update xgc-devel version requested by wdmapp package

---

spack/wdmapp/packages/wdmapp/package.py

This adds two variants to the package that make it possible to select whether legacy xgc1 and tau (which is added here) will be built.
I'm actually a bit torn as to whether adding variants is a good idea, so maybe this should be reconsidered at some point. Generally, variants make it harder to test / get all combinations to work right. In this case, though, all they do is enable or disable dependent packages, so they should be relatively harmless.
Mentioning @khuck so he knows that tau will now be included in the spec (optional, but on by default).

add some variants to wdmapp metapackage

---

summit/spack/packages-extended.yaml

Tau needs binutils with +libiberty and +headers to demangle symbols.

summit: system binutils has +libiberty +headers

---

summit/spack/packages-extended.yaml

That makes `packages-extended.yaml` consistent with `packages.yaml` in
that aspect.
It also appears that it makes a real difference in that tau wasn't
working correctly with the paths method, though that has now been
updated in tau.

spack: use spectrum-mpi via modules on Summit

---

spack/wdmapp/packages/codar-cheetah/package.py
spack/wdmapp/packages/effis/package.py

The codar-cheetah package is based on the spack 0.14.2 package with changes from wdmapp/spack. Effis is not in spack/spack.
@suchyta1 are there any other packages we will need to install effis with the `wdmapp` package?

add effis and codar-cheetah packages from wdmapp/spack

---

spack/wdmapp/packages/coupler/package.py
spack/wdmapp/packages/gene/package.py
spack/wdmapp/packages/wdmapp/package.py
spack/wdmapp/packages/xgc-devel/package.py

This PR adds 
- support for installing the separate coupler and the associated branches of xgc and gene via spack, and 
- aimos developer install documentation.
One issue was hit in `wdmapp/package.py` that seems to be related to an existing spack concretization bug.  Specifically, if `depends_on('hdf5 +hl')` was not specified with the passthrough variant on and off then spack would fail to concretize the dependency in both cases.

support passthrough coupler: spack and instructions

---

spack/wdmapp/packages/effis/package.py
spack/wdmapp/packages/wdmapp/package.py
summit/spack/packages-extended.yaml

effis requires python > 2.7.12 (another version > 2.7.5 may also work too) - see
https://github.com/wdmapp/effis/issues/2
The wdmapp meta package needed the same dirty hack that was used for hdf5; if the 'passthrough'
variant was not specified there were concretization errors.  Once we merge the
gene and xgc 'rpi' branches we can avoid the 'passthrough' (or similar) variants
that require divergent versions of packages.

wdmapp: add effis

---

rhea/spack/compilers.yaml
rhea/spack/packages.yaml

This supports building the `wdmapp` metapackage on rhea (works for me (tm), anyway ;) )
This has a rather minimal `package.yaml` which does not even use the system openmpi, but instead builds its own openmpi, using the same configuration as the system one.
The reason for this is that spack v.14 gets confused when trying to use the system openmpi, or other installed packages / modules on rhea, because those were installed by an older version of spack, which does provide some special information in a `.spack` directory, but not all that v.14 expects. This issue should be fixed in recent spack `develop`, but we'd rather not require the cutting edge spack. See https://github.com/spack/spack/pull/16954
@cwsmith @suchyta1

spack: add config files for rhea

---

rhea/spack/packages.yaml
spack/wdmapp/packages/wdmapp/package.py
summit/spack/packages-extended.yaml
summit/spack/packages.yaml

The "useful" EFFIS needs to be built with python=type=full, so that
job composition/submission etc is available.
Unfortunately, it is not possible to do this variant in the metapackage,
since it requires python3, but xgc requires python2 via petsc, and spack
does not allow for that.
Instead the defaults for EFFIS are set in packages.yaml so that a separate
`spack install effis` will do the right thing.

spack: don't include effis in wdmapp meta package

---

rhea/spack/packages.yaml

- Tau variant `-papi` is because of #51 
- Newer version of `libfabric` and RDMA don't work properly (yet) on Rhea.

libfabric@1.6.1 on Rhea

---

rhea/spack/packages.yaml
spack/wdmapp/packages/effis/package.py
spack/wdmapp/packages/wdmapp/package.py
spack/wdmapp/packages/xgc-devel/package.py

I added a `+effis` variant to install (non-passthrough) XGC and GENE with EFFIS turned on, and made some improvements to the EFFIS package file. A `spack install effis` is still needed for the composition front-end, but that of course can't be added to the same package due to the single concretization.

+effis installation version

---

spack/wdmapp/packages/xgc-devel/package.py

This isn't pretty, but XGC does have that many (and more) compile
time options, so this makes them accessible as variants.

spack: handle lots of variants to xgc-devel

---

docs/machines/aimos.rst
docs/machines/longhorn.rst
docs/machines/note-olcf-shared-spack.rst
docs/machines/note-olcf-spack-dir.rst
docs/machines/rhea.rst
docs/machines/summit.rst
docs/spack/adding-wdmapp.rst
docs/spack/cloning-wdmapp-config.rst
docs/spack/installing-spack.rst
docs/spack/setup-intro.rst
docs/spack/setup.rst

This updates the docs to use common text blocks so that each machine has a single page that avoids referring to generic instructions but rather includes the necessary text directly (however, the change is only for the spack setup part, it should also be done for the actual "Building wdmapp" part).
It also fixes a bunch of other bits and pieces along the way.
Still needs more work, but I'll call it progress...

docs updates

---

spack/wdmapp/packages/effis/package.py

EFFIS should have the `extends('python')` command for loading it into `PYTHONPATH`. I accidentally deleted this before.

Add extends('python') to EFFIS

---

rhea/spack/packages.yaml
spack/wdmapp/packages/effis/package.py
spack/wdmapp/packages/wdmapp/package.py

This makes the EFFIS Spack variants simpler, as well as makes installation more robust if Python isn't actually needed, cf. #61 when an Anaconda Python 2 distribution is used.

Update effis options so Python can be turned off altogether

---

spack/wdmapp/packages/effis/package.py

Very minor here. Title says it all.

Add conflicts to make sure +compose uses +python in EFFIS

---

docs/machines/cyclone-run.rst
docs/machines/rhea.rst

A minor fix to the docs, as well as instructions on how to use the E4S build cache on rhea

docs updates for e4s build cache

---

summit/spack/packages-extended.yaml
summit/spack/packages.yaml

The `libpng` part was removed because ADIOS2 needs `libpng > 1.6`, but `matplotlib` can use an older version, and the path to `1.5.13` was causing Spack to try to use that and throwing an error.

Update Summit packages.yaml for new EFFIS variants

---

docs/effis/dashboard.rst

I had copied and pasted the wrong thing for the link about deploying the dashboard.

Fix wrong link in documentation

---

docs/build/build.rst

The non-public code installs require SSH keys. Many people will have already have uploaded them to GitHub but I added a note about it.

Documentation about GitHub SSH keys

---

docs/machines/note-olcf-spack-dir.rst

The scratch dir is `/gpfs/alpine/scratch/$USER/<project>/spack-stage` on rhea and summit.

olcf: swap order of user and project in scratch path

---

spack/wdmapp/packages/effis/package.py

The effis preprocessor converts effis pragmas in the source code to effis C++/Fortran api calls.  If the effis front-end (supports job composition and execution/submission) is enabled then Python 3 is required.
Without this fix Effis CMake finds system python 2.7.5 on Rhea which is too old.  That error appears as:
```
-- Found Python: /usr/bin/python2.7 (found version "2.7.5") found components:  Interpreter 
-- Performing Test exists_gnu
-- Performing Test exists_gnu - Success
-- Configuring done
CMake Error at examples/simple/Fortran/CMakeLists.txt:7 (add_executable):
Cannot find source file:
/tmp/cwsmith/spack-stage/spack-stage-effis-develop-o6uvusyc4ad5lhkn7syeybpf6frydvgh/spack-build/examples/simple/Fortran/reader-effis.F90
Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h …
```

effis always needs python2.7.12 for the preprocessor

---

spack/wdmapp/packages/camtimers/package.py
spack/wdmapp/packages/effis/package.py
spack/wdmapp/packages/gene/package.py
spack/wdmapp/packages/pspline/package.py
spack/wdmapp/packages/wdmapp/package.py
spack/wdmapp/packages/xgc-devel/package.py

FWIW, I don't necessarily like tagging everything with `wdmapp-0.1.0`. I think for gene and xgc-devel, it's needed as to not confuse it with any other official releases. But for EFFIS, you could declare a generic release, and we could use that, and for pspline and camtimers, I don't think they're really wdmapp specific, so I could also give them just a generic version.

spack: tag gene, xgc-devel, effis, camtimers, pspline wdmapp-0.1.0 release

---

docs/machines/rhea.rst
docs/machines/summit.rst

`wdmapp` and `effis +compose` are using different versions of python. Loading effis after wdmapp is necessary to run `effis-compose.py` successfully.
If effis is loaded before wdmapp then running `effis-compose.py` produces the following error:
```$ effis-compose.py run_1.yaml
Traceback (most recent call last):
File "/autofs/nccs-svm1_home1/cwsmith/develop/wdmapp/spack/opt/spack/linux-rhel7-sandybridge/gcc-8.4.0/effis-develop-rppt4ve65dvbk262wentbdwu4n7uhs2j/bin/effis-compose.py", line 9, in <module>
import codar.cheetah as cheetah
File "/autofs/nccs-svm1_home1/cwsmith/develop/wdmapp/spack/opt/spack/linux-rhel7-sandybridge/gcc-8.4.0/codar-cheetah-develop-5lspai3aymvqhjzehsw2uioethho7eiw/lib/python3.7/site-packages/codar/cheetah/__init__.py", line 5, in <module>
from codar.cheetah.model …
```

docs: swap order of spack loads to avoid python error

---

rhea/spack/packages.yaml
summit/spack/packages-extended.yaml

Adding the `python@2:7:12:` dependency for the `effis` that installs with `wdmapp` reintroduced the issue with Anaconda causing a problem by picking up a `libgfortran` in Anaconda. I've fixed the this in Rhea's extend `packages.yaml` and I'm figuring out what does and doesn't work on Summit.

Remove Anaconda for Python 2.7

---

spack/wdmapp/packages/gem/package.py
spack/wdmapp/packages/perfstubs/package.py

It's a (temporary) workaround to build a version of perfstubs via spack that can be included in spack/cmake-based projects easily.

spack: add custom perfstubs

---

summit/spack/packages-extended.yaml
summit/spack/packages.yaml

Maintaining two `packages.yaml` is, unsurprisingly, error-prone. This makes the two versions more easily diff-able, and
makes the adios2 builds consistent between the two of them.

Summit packages.yaml updates

---

docs/spack/installing-spack.rst

This PR changes the docs to clone/use spack v0.15.4.

Documentation: use spack v0.15.4

---

spack/wdmapp/packages/wdmapp/package.py

To my knowledge, this isn't actually used, and the latest tau spack package
doesn't have the variant. It could probably be re-added, if someone needs it.
Fixes #89.

spack: don't require +adios2 variant of tau

---

spack/wdmapp/packages/coupler/package.py
spack/wdmapp/packages/gene/package.py
spack/wdmapp/packages/wdmapp/package.py
spack/wdmapp/packages/xgc-devel/package.py

The following script/commands will install wdmapp for running the cyclone problem with xgc-coupler-gene on summit.
```shell
#!/bin/bash -x
externalCpl=$1
[[ "$externalCpl" != "on" &&
"$externalCpl" != "off"  ]] &&
echo "Usage: $0 <externalCpl=on|off>" &&
exit 1;
date=`date +%F-%H-%M`
wdmDir=$SCRATCH/wdmExtCpl_${date}
mkdir -p $wdmDir
cd $wdmDir
git clone -b v0.15.4 https://github.com/spack/spack.git
git clone -b extCplv0154 git@github.com:SCOREC/wdmapp-config.git
cd spack
export SPACK_ROOT=$PWD
source $SPACK_ROOT/share/spack/setup-env.sh
which spack # sanity check
#yaml files
mkdir $SPACK_ROOT/etc/spack/linux
cp $wdmDir/wdmapp-config/summit/spack/*.yaml $_
cd $_
mv packages.yaml packages.minimal.yaml
ln -s packages-extended.yaml packages.yaml
#add the wdmapp repo
spack repo add --scope …
```

install coupler that supports successfull xgc-gene coupled cyclone runs
